# Generated by Django 4.0.3 on 2022-04-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0004_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses_id',
            field=models.IntegerField(default=0),
        ),
    ]
