# Generated by Django 4.0.3 on 2022-04-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0005_profile_courses_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrollment',
            field=models.ManyToManyField(to='studybuddy.courses'),
        ),
    ]
