# Generated by Django 4.0.3 on 2022-04-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0006_profile_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='courses_id',
        ),
    ]
