# Generated by Django 4.0.2 on 2022-04-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0007_remove_profile_courses_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(to='studybuddy.Courses'),
        ),
    ]
