# Generated by Django 4.0.4 on 2022-05-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0009_profile_toggled_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='toggled_courses',
            field=models.ManyToManyField(blank=True, related_name='toggled_courses', to='studybuddy.courses'),
        ),
    ]
