# Generated by Django 4.0.3 on 2022-05-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0010_alter_profile_toggled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='instructor',
        ),
    ]
