# Generated by Django 4.0.3 on 2022-05-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0012_courses_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='instructor',
        ),
    ]
