# Generated by Django 3.2.13 on 2022-05-03 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0014_alter_schedule_study_buddies'),
        ('studybuddy', '0014_courses_instructor'),
    ]

    operations = [
    ]
